# Generated by Django 5.1.3 on 2024-12-05 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Manage Client', 'verbose_name_plural': 'Manage Clients'},
        ),
    ]
