# Generated by Django 5.1.3 on 2024-12-23 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_client_options_alter_client_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Manage Agency', 'verbose_name_plural': 'Manage Agencies'},
        ),
    ]
