# Generated by Django 5.1.3 on 2024-11-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menukit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
    ]
