# Generated by Django 5.1.3 on 2024-11-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menukit', '0002_category_deleted_subcategory_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
