# Generated by Django 5.1.3 on 2024-12-01 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menukit', '0003_subcategory_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menus'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'SubMenu', 'verbose_name_plural': 'SubMenus'},
        ),
    ]
