# Generated by Django 5.1.3 on 2024-12-01 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menukit', '0004_alter_category_options_alter_subcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Manage Menu', 'verbose_name_plural': 'Manage Menus'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Manage SubMenu', 'verbose_name_plural': 'Manage SubMenus'},
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='menukit.category', verbose_name='Menu'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='ingrediants',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
