# Generated by Django 5.1.3 on 2024-12-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menukit', '0005_alter_category_options_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
