# Generated by Django 5.1.3 on 2024-12-10 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menukit', '0006_alter_subcategory_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='ingrediants',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Menu Name'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='menukit.category', verbose_name='Menu Name'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='SubMenu Name'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='price',
            field=models.FloatField(null=True, verbose_name='SubMenu Price'),
        ),
    ]
