# Generated by Django 5.1.3 on 2024-12-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'verbose_name': 'Manage Agency', 'verbose_name_plural': 'Manage Agencies'},
        ),
    ]
