# Generated by Django 5.1.3 on 2024-12-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_created_at_orderitem_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Manage Order', 'verbose_name_plural': 'Manage Orders'},
        ),
    ]
