# Generated by Django 5.1.3 on 2024-12-05 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Manage Kitchen', 'verbose_name_plural': 'Manage Kitchen'},
        ),
    ]
