# Generated by Django 5.1.3 on 2024-12-10 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_delivery_address_alter_client_name_and_more'),
        ('menukit', '0007_remove_subcategory_ingrediants_alter_category_name_and_more'),
        ('orders', '0009_alter_orderitem_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_client', to='client.client', verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agency Name'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menukit.category', verbose_name='Menu Name'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menukit.subcategory', verbose_name='SubMenu Name'),
        ),
    ]
