# Generated by Django 5.1.3 on 2024-12-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_client_alter_order_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Manage Kitchen (Orders Items)', 'verbose_name_plural': 'Manage Kitchen (Orders Items)'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='special_instructions',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='special_request',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
