# Generated by Django 5.1.3 on 2024-12-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='special_request',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
