# Generated by Django 5.1.3 on 2024-12-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_orderitem_special_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='special_request',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
