# Generated by Django 5.1.3 on 2025-04-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_orderitem_special_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dietary_restrictions',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
