# Generated by Django 5.1.3 on 2024-12-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_ticket', '0002_alter_attachment_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='support_ticket',
            options={'verbose_name': 'Manage Support Ticket', 'verbose_name_plural': 'Manage Support Tickets'},
        ),
    ]
