# Generated by Django 5.1.3 on 2024-12-10 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_ticket', '0003_alter_support_ticket_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='support_ticket',
            name='category',
            field=models.CharField(choices=[('Technical', 'Technical'), ('Billing', 'Billing'), ('Account', 'Account'), ('General', 'General')], default='General', max_length=100, verbose_name='Ticket Category'),
        ),
        migrations.AlterField(
            model_name='support_ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_supoort_ticket', to=settings.AUTH_USER_MODEL, verbose_name='Agency'),
        ),
    ]
